### ISSUE TITLE
Use absolute positioning instead of fixed

### ISSUE THREAD

**Issue by Eibwen** [juliankrispel/react-text-selection-popover#13]
Or perhaps an option for this?

Specifically my current settings if I select text, then scroll, the position is fixed in the display port.  But if you were to calculate the absolute positioning values, it would scroll to seem to be attached to the selected text

**Comment by juliankrispel** [comment]
Hey there. Thanks for opening this. The problem with absolute positioning is that it's relative to how the parent elements are positioned. What we could do however is recalculate the positioning if a scroll happens in the dom element that is `selectionRef`

**Comment by Eibwen** [comment]
Ah yes, and that workaround would be pretty easy for me to implement outside of your library.

A side question, whats the easiest way to get the selected text?  Just something starting with?:
```
function getSelectionRange() {
  var selection;
  if (window.getSelection) {
    selection = window.getSelection();
  } else if (document.selection) {
    selection = document.selection.createRange();
  }
...
}
```

Or do you know of a more React-y way to do that?

**Comment by juliankrispel** [comment]
there isn't a react-y way of doing it :)
