### ISSUE TITLE
Another value for "defaultDirection"

### ISSUE THREAD

**Issue by Eibwen** [juliankrispel/react-text-selection-popover#14]
I'm using your library on a large page of code, and for my usage I expect to sometimes select over 1 page worth of text.

So I was thinking it would be nice to have the library detect the selection direction (like if I click at the top, hold drag downward vs upward), I'd probably call it `defaultDirection="mouse"`, but obviously up to you if you implement or accept a pull request

I haven't looked at your code yet, but I'd imagine it would be simple to decide which one of these are higher up on the screen or in the DOM, and determine if it uses the `"above"` or the `"below"` logic
```
  var selectionStart = selection.anchorNode;
  var selectionEnd = selection.focusNode;
```

**Comment by juliankrispel** [comment]
I was actually thinking of removing defaultdirection and instead exposing the positioning method itself so that the user can choose how to position the popup. This could be useful for a range of different scenarios

**Comment by Eibwen** [comment]
Ah that would be a much more versatile solution indeed.  I'd suggest giving examples of simple function implementations to allow copy/paste of common scenarios, or where it doesn't matter too much to the user (well you'd inherently have that in your example link)

**Comment by juliankrispel** [comment]
@Eibwen exactly what I was thinking!

**Comment by juliankrispel** [comment]
@Eibwen it's been a while (I've been pretty busy) but I've finally had the need to implement configurable placement. I call it [placement strategies, please have a look here](https://github.com/juliankrispel/react-text-selection-popover#positioning-the-popover) this should work for you!
