### ISSUE TITLE
Avoid locking the react-dom version

### ISSUE THREAD

**Issue by zeropaper** [juliankrispel/react-text-selection-popover#22]
https://github.com/juliankrispel/react-text-selection-popover/blob/7f86b20bb567d3bb5b4cab86fdd5ff8ce607d5d9/package.json#L39

It would be better if the version of react-dom was not locked to 16.3.0 :)

**Comment by juliankrispel** [comment]
fair dos I'll have a look

**Comment by juliankrispel** [comment]
sry I didn't see this before, I released this as a minor patch as `react-text-selection-popover@1.2.5`
