### ISSUE TITLE
button onClick is not working Inside Popover

### ISSUE THREAD

**Issue by fxnoob** [juliankrispel/react-text-selection-popover#25]
`<Popover
                isOpen={this.state.isOpen}
                onTextSelect={this.onTextSelect}
                onTextUnselect={() => this.setState({ isOpen: false })}
                onClick={this.handleClick}>
            >
                <button onClick={this.handleClick}>{this.state.selectedText}!</button>
            </Popover>`

**Comment by juliankrispel** [comment]
[working sandbox here](https://codesandbox.io/s/n5jz2myl4m)!

![totally-pressed-dude](https://user-images.githubusercontent.com/1188186/56554197-d54c0f00-6588-11e9-87c1-bbac09dcaaf7.gif)
