### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by dhinesh-agentz** [juliankrispel/react-text-selection-popover#32]
when am trying to run with ur package getting following error !!
![Screenshot from 2019-10-14 19-19-36](https://user-images.githubusercontent.com/53560536/66756437-a4a1be00-eeb7-11e9-9ce9-461f6e3f2d78.png)

**Comment by RomanShabanov** [comment]
do you use server side rendering?

**Comment by juliankrispel** [comment]
this library isn't really made for ssr sry
