### ISSUE TITLE
Feature: add autoHide prop

### ISSUE THREAD

**Issue by juliankrispel** [juliankrispel/react-text-selection-popover#4]
Automatically hide/show popover when text is selected/unselected

**Comment by sunilhari** [comment]
Hi, I believe i can work on this @juliankrispel

**Comment by juliankrispel** [comment]
@sunilhari sweet!

Here's what I have in mind:

- `autoHide=true` should be default (which would be a breaking change (so a major version increase)
-  when `autoHide=true` then `isOpen` prop is ignored (and should probably throw a prop warning if defined)
-  when `autoHide=true` instead of using `this.props.isOpen` `this.state.isOpen` is used and set when text is selected/unselected
- to disable `autoHide` one just has to explicitly set `autoHide=false`

**Comment by juliankrispel** [comment]
That'd reduce the minimal usecase to just

`<Popover>My stuff here</Popover>` you wouldn't need any configuration for some usecases 😍

**Comment by sunilhari** [comment]
Will try working on it right away @juliankrispel  and will raise a PR.Headsup please bare if i make some mistakes

**Comment by juliankrispel** [comment]
@sunilhari absolutely no worries you have my support every step of the way - I added you as collaborator!

**Comment by sunilhari** [comment]
Thank you @juliankrispel

**Comment by sunilhari** [comment]
@juliankrispel  A small doubt.Does that mean for i`sOpen` to work do we they have to explicitly give `autoHide` to `false`

**Comment by juliankrispel** [comment]
@sunilhari yes exactly! Although how about this - if isOpen is defined it overrides autoHide ...

**Comment by juliankrispel** [comment]
But then we should really throw a warning because autoHide will not work as expected ...

**Comment by sunilhari** [comment]
@juliankrispel  what about `selectionRef`.Still this would be need to be passed right??

**Comment by juliankrispel** [comment]
If you look at the docs - it’s optional - it defaults to ‘document’

**Comment by sunilhari** [comment]
@juliankrispel   I could not get to work with out adding `selectionRef`.Could you guide through where am missing .I will submit a PR and please review the change and kindly let me know

**Comment by juliankrispel** [comment]
weeehaaa @sunilhari :+1:
