### ISSUE TITLE
why no click is encouraged?

### ISSUE THREAD

**Issue by asimkt** [juliankrispel/react-text-selection-popover#43]
Why are we doing https://github.com/juliankrispel/react-text-selection-popover/blob/ea84ffd388fcf6a6c1fd4344bb60bbdcd8114a22/src/index.js#L96?
If user wants to control the click on top of toolbar, we should allow it, right?

And

```
containerNode | React.ref
-- | --
```
needed `.current` instead of the ref object.

**Comment by juliankrispel** [comment]
this'll be entirely under your control with the 2.0 release

**Comment by asimkt** [comment]
That's really good to know. What's the release plan for v2?

**Comment by juliankrispel** [comment]
@asimkt I just released it :)

Lmk if that solves your issues, will close for now.
