### ISSUE TITLE
MouseUp outside of selectionRef

### ISSUE THREAD

**Issue by wouterraateland** [juliankrispel/react-text-selection-popover#44]
**Problem:**
When `selectionRef` is set, the target for the mouseUp event is set to the corresponding element. Hence, when releasing the mouse when the cursor is outside of `selectionRef.current`, the `mouseUp` event is not triggered. In this case, the popup becomes non-interactive due to `style.pointerEvents = "none";`.

**Possible solution:**
Change the `target` prop of the mouseUp `EventListener` component to either `window` or `document`. This would retain the behavior of making the popup non-interactive while selecting, and it will make the popup always interactive when the mouse is released.

If it fits the intended behavior, this minor change would be much appreciated :)

**Comment by juliankrispel** [comment]
@wouterraateland could you give us a codesandbox?

**Comment by juliankrispel** [comment]
@wouterraateland the 2.0 release has changed this project from the ground up and does do very little now. Fixing your issue should now really be under your control. Will close this issue for now, lmk if there's anything I can clarify.
