### ISSUE TITLE
Seem to not run on React 16.13.1

### ISSUE THREAD

**Issue by edwinramirez-fullstack** [juliankrispel/react-text-selection-popover#46]
My project was created on React version 16.13.1 and I haven't been able to make this module run in even it's most simplest form. 
I installed with `yarn add react-text-selection-popover` and my component goes like this:
```
import Popover from 'react-text-selection-popover';
class MyComponent extends Component {
// Goes straight to render
render() {
<React.Fragment>
...//Simple divs and CSS, nothing fancy
<Popover>
  Just some text 
</Popover>
</React.Fragment>
}}....
```

No text is rendered. No console errors logged. Just a warning: 

```
react_devtools_backend.js:2430 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: WindowDimensions, WithContentRect
```

Any advice is deeply appreciated.

**Comment by juliankrispel** [comment]
Will fix in the upcoming release

**Comment by juliankrispel** [comment]
This is now fixed @edwinramirez-fullstack with the new release -> `2.0.0` 

Although much simplified, the API has changed significantly. Please have a look at the readme to see how it works. Or if you'd like to use a hook instead of a component with a render prop, check out [use-text-selection](https://github.com/juliankrispel/use-text-selection)
