### ISSUE TITLE
Unintended behaviour in Chrome Mobile

### ISSUE THREAD

**Issue by Jigar3** [juliankrispel/react-text-selection-popover#50]
Hey, as you can see below on mobile, it renders both popovers. Anyway to suppress the one which chrome enables by default.

![WhatsApp Image 2021-05-03 at 11 14 28 PM](https://user-images.githubusercontent.com/32068121/116912126-6ddff400-ac65-11eb-8107-117c59ec9df1.jpeg)

**Comment by juliankrispel** [comment]
@Jigar3 interesting, will have a look

**Comment by juliankrispel** [comment]
@Jigar3 have you tried this https://stackoverflow.com/a/28748222 ?

**Comment by juliankrispel** [comment]
closing since this behaviour can be prevented by using event apis
